os:
  - linux
addons:
  apt:
    packages:
      - git-ftp
script:
  - git config git-ftp.url "ftpes://rettungscorps.ch/rc"
  - git config git-ftp.user $FTP_USER
  - git config git-ftp.password $FTP_PASSWORD
  - git-ftp push -vv --insecure || git-ftp init -vv --insecure && git-ftp push -vv --insecure
branches:
  only:
    - master
notifications:
  email:
    on_success: change
    on_failure: change
