os:
  - linux
addons:
  apt:
    packages:
      - git-ftp
script:
  - git config git-ftp.url "ftp://rettungscorps.ch/rc"
  - git config git-ftp.user $FTP_USER
  - git config git-ftp.password $FTP_PASSWORD
  - git ftp catchup -vv
  - git ftp push -vv
branches:
  only:
    - master
notifications:
  email:
    on_success: change
    on_failure: change
