os:
  - linux
addons:
  apt:
    packages:
      - git-ftp
script:
  - git ftp push -vv --user $FTP_USER --passwd $FTP_PASSWORD ftp://rettungscorps.ch/rc
branches:
  only:
    - master
notifications:
  email:
    on_success: change
    on_failure: change
